/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ClimateEducationApp;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class CF_UserUI extends javax.swing.JFrame {
    int numberOfFlights;
    double totalFlightDuration, electricBill, gasBill, oilBill, mileage, totalFootprint, creditScore;
    String title, choiceNewspaper, choiceAluminium;
    private List<JTextField> textFields;

    // Creates new form CF_UserUI
    public CF_UserUI() {
        initComponents();

        textFields = new ArrayList<>();
        textFields.add(flighttakenTF);
        textFields.add(flightDurationTF);
        textFields.add(electricBillTF);
        textFields.add(gasBillTF);
        textFields.add(carMileageTF);
        textFields.add(oilBillTF);
        textFields.add(NewspaperTF);
        textFields.add(ALTF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flighttakenTF = new javax.swing.JTextField();
        flightDurationTF = new javax.swing.JTextField();
        electricBillTF = new javax.swing.JTextField();
        gasBillTF = new javax.swing.JTextField();
        carMileageTF = new javax.swing.JTextField();
        oilBillTF = new javax.swing.JTextField();
        NewspaperTF = new javax.swing.JTextField();
        ALTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Carbon Footprint");

        jLabel2.setText("Answer the question below to retrieve your score and title!");

        jLabel3.setText("Please enter the number of times you've flown on a plane this year :");

        jLabel4.setText("Please enter the total duration of all flights in hours:");

        jLabel5.setText("Enter your monthly electric bill $:");

        jLabel6.setText("Enter your monthly gas bill $:");

        jLabel7.setText("Enter your car's mileage for this year:");

        jLabel8.setText("Do you recycle newspaper? Enter Yes/No");

        jLabel9.setText("Do you recycle aluminium and tin? Enter Yes/No");

        jLabel10.setText("Enter your monthly oil bill $");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flighttakenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightDurationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electricBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gasBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oilBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewspaperTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ALTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flighttakenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightDurationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electricBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gasBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(carMileageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oilBillTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewspaperTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ALTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // InputMismatchException error handling for Integer input fields
    private class IntegerInputVerifier extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            JTextField textField = (JTextField) input;
            String text = textField.getText().trim();

            try {
                // Attempt to parse the input as an integer
                int intValue = Integer.parseInt(text);
                // Perform additional validation if needed (e.g., range checks)
                if (intValue >= 0) {
                    return true; // Input is valid
                } else {
                    showErrorDialog("Please enter a non-negative integer value.");
                    return false; // Input is invalid
                }
            } catch (NumberFormatException e) {
                showErrorDialog("Please enter a valid integer value.");
                return false; // Input is invalid
            }
        }
    }

    // InputMismatchException error handling for Double input fields
    private class DoubleInputVerifier extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            JTextField textField = (JTextField) input;
            String text = textField.getText().trim();

            try {
                // Attempt to parse the input as a double
                double doubleValue = Double.parseDouble(text);
                // Perform additional validation if needed (e.g., range checks)
                if (doubleValue >= 0) {
                    return true; // Input is valid
                } else {
                    showErrorDialog("Please enter a non-negative double value.");
                    return false; // Input is invalid
                }
            } catch (NumberFormatException e) {
                showErrorDialog("Please enter a valid double value.");
                return false; // Input is invalid
            }
        }
    }

    // InputMismatchException error handling for Boolean input fields
    private class BooleanInputVerifier extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            JTextField textField = (JTextField) input;
            String text = textField.getText().trim().toLowerCase(); // Convert to lowercase for case-insensitivity

            if (text.equals("yes") || text.equals("no")) {
                return true; // Input is valid
            } else {
                showErrorDialog("Please enter either 'Yes' or 'No'.");
                return false; // Input is invalid
            }
        }
    }

    // Checks if no fields are empty
    private boolean validateTextFields() {
        for (JTextField textField : textFields) {
            if (textField.getText().trim().isEmpty()) {
                showErrorDialog("Please fill in all information to retrieve your SCORE and TITLE.");
                return false;
            }
        }
        return true;
    }
    
    // Displays error message for input error
    private void showErrorDialog(String errorMessage) {
        JOptionPane.showMessageDialog(null, errorMessage, "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    
    // Exit button method
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserInterface UI = new UserInterface();
        UI.setVisible(true);
        UI.pack();
        UI.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Submit button method
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if (validateTextFields() == true &&
            new IntegerInputVerifier().verify(flighttakenTF)==true&&
            new DoubleInputVerifier().verify(flightDurationTF)==true&&
            new DoubleInputVerifier().verify(electricBillTF)==true&&
            new DoubleInputVerifier().verify(gasBillTF)==true&&
            new DoubleInputVerifier().verify(carMileageTF)==true&&
            new DoubleInputVerifier().verify(oilBillTF)==true&&
            new BooleanInputVerifier().verify(NewspaperTF)==true&&
            new BooleanInputVerifier().verify(ALTF)==true
            ) {            
                numberOfFlights = Integer.parseInt(flighttakenTF.getText());
                totalFlightDuration = Double.parseDouble(flightDurationTF.getText());
                electricBill = Double.parseDouble(electricBillTF.getText());
                gasBill = Double.parseDouble(gasBillTF.getText());
                oilBill = Double.parseDouble(oilBillTF.getText());
                mileage = Double.parseDouble(carMileageTF.getText());
                choiceNewspaper = NewspaperTF.getText();
                choiceAluminium = ALTF.getText();
                calculate();
                displayResults();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    // Calculates carbon footprint using all user inputs
    public void calculate() {
        FlightFootprint calculator = new FlightFootprint(totalFlightDuration, numberOfFlights, 0);
        double totalFlightFootprint = calculator.calculatefootprint();

        HouseFootprint calculation = new HouseFootprint(electricBill, gasBill, oilBill);
        double totalHouseFootprint = calculation.calculateFootprint();

        CarbonFootprint calculateCarFootprint = new CarbonFootprint(mileage);
        double totalCarFootprint = calculateCarFootprint.calculateCarFootprint();

        Recycle recycle = new Recycle(choiceNewspaper, choiceAluminium);
        double totalNewspaperFootprint = recycle.calculateNewspaper();
        double totalAluminiumFootprint = recycle.calculateAluminium();

        double footprint = totalHouseFootprint + totalCarFootprint
                + totalFlightFootprint + totalNewspaperFootprint + totalAluminiumFootprint;
        this.totalFootprint = footprint;

        double credit = footprint * 0.069;
        this.creditScore = credit;
    }

    // Displays credit score and awards title
    public void displayResults() {
        // lower the credit score, better the titles 
        JOptionPane.showMessageDialog(null, " Your total carbon footprint of the year is " + totalFootprint + " metric tons of CO2");
        if (creditScore <= 2000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Climate Champion";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else if (creditScore <= 4000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Earth Advocate";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else if (creditScore <= 6000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Carbon Neutral Pro";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else if (creditScore <= 8000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Green Guardian";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else if (creditScore <= 10000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Footprint Fighter";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else if (creditScore <= 11000) {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Eco Warrior";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        } else {
            JOptionPane.showMessageDialog(null, "Your total carbon credit score is " + this.creditScore);
            title = "Sustainable Hero";
            JOptionPane.showMessageDialog(null, "You have earned the title: " + title);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALTF;
    private javax.swing.JTextField NewspaperTF;
    private javax.swing.JTextField carMileageTF;
    private javax.swing.JTextField electricBillTF;
    private javax.swing.JTextField flightDurationTF;
    private javax.swing.JTextField flighttakenTF;
    private javax.swing.JTextField gasBillTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField oilBillTF;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

}
