package com.mycompany.ClimateEducationApp;
/**
 *
 * @author User
 */

public class CI_User extends javax.swing.JFrame {
    StringBuilder newsBuilder = new StringBuilder();
    StringBuilder infoBuilder = new StringBuilder();

    // Creates new form CI_User
    public CI_User() {
        initComponents();
        displayNews();        
        Blog.setEditable(false);
        Blog.setContentType("text/html");        
        Blog.setText(newsBuilder.toString());
    }

    
    // Display the news in the JTextArea  
    private void displayNews() {      
        newsBuilder.append("<html><b><font size='5'>--------- Temperature News ---------</font></b><br>");
        newsBuilder.append("Kuala Lumpur 27°C<br>");
        newsBuilder.append("Johor Baru: 25°C<br>");
        newsBuilder.append("Ipoh: 26°C<br>");
        newsBuilder.append("Kuching: 26°C<br><br>");

        newsBuilder.append("<b><font size='5'>--------- Energy Breakthrough News ---------</font></b><br>");
        newsBuilder.append("SCIENTISTS DISCOVER NUCLEAR ENERGY BREAKTHROUGH<br>");
        newsBuilder.append("Nuclear scientists say this is a key step toward producing clean and potentially cheap power,<br>");
        newsBuilder.append("though they warn the fledgling form of energy still has a long way to go before<br>");
        newsBuilder.append("it becomes a viable option. <br><br>");

        newsBuilder.append("<b><font size='5'>--------- Plastic Waste News ---------</font></b><br>");
        newsBuilder.append("Since 2018, more than 1,000 organisations have given their backing to the Global Commitment,<br>");
        newsBuilder.append("led by the Foundation in partnership with the UN Environment Programme, to stop plastic<br>");
        newsBuilder.append("packaging from becoming waste.<br>");
        newsBuilder.append("And also increasing their use of recycled plastics by 1.5 million tonnes per annum<br></html>");

        // Set the text of the JTextArea
        Blog.setText(newsBuilder.toString());
    }
    
    // Display the information in the JTextField   
    private void displayInfo() {    
        infoBuilder.append("<html><b><font size='7'>-------- Interactive Info System --------</font></b><br>");
        infoBuilder.append("<b><font size='5'>--------- Understanding Climate Change ---------</font></b><br>");
        infoBuilder.append("Climate change is a long-term change in the average weather patterns.<br>");
        infoBuilder.append("It is primarily caused by human activities, including the burning of fossil fuels.<br>");

        infoBuilder.append("<b><font size='5'>--------- Energy Breakthrough News ---------</font></b><br>");
        infoBuilder.append("To reduce carbon emissions, individuals can use energy-efficient appliances<br>");
        infoBuilder.append("drive less, and support renewable energy sources.<br>");
        
        infoBuilder.append("<b><font size='5'>--------- Sustainable Living ---------</font></b><br>");
        infoBuilder.append("Sustainable living involves making choices that have a positive impact on the environment.<br>");
        infoBuilder.append("This includes reducing waste, conserving energy, and supporting eco-friendly products.<br></html>");
        
        // Set the text of the JTextField
        Blog.setText(infoBuilder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NewsFeedBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Blog = new javax.swing.JEditorPane();
        shareButton = new javax.swing.JButton();
        infograf = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        NewsFeedBtn.setText("NewsFeed");
        NewsFeedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewsFeedBtnActionPerformed(evt);
            }
        });

        InfoBtn.setText("Info System");
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(Blog);

        shareButton.setText("Share");
        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });

        infograf.setText("Infographics");
        infograf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infografActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(NewsFeedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infograf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(shareButton)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewsFeedBtn)
                    .addComponent(InfoBtn)
                    .addComponent(shareButton)
                    .addComponent(infograf))
                .addGap(1, 1, 1))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blog");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton)
                        .addGap(16, 16, 16)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // NewsFeed button method
    private void NewsFeedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewsFeedBtnActionPerformed
        Blog.setText("");
        displayNews();
    }//GEN-LAST:event_NewsFeedBtnActionPerformed

    // Info System button method
    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        Blog.setText("");
        displayInfo();
    }//GEN-LAST:event_InfoBtnActionPerformed

    // Exit button method
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        UserInterface UI = new UserInterface();
        UI.setVisible(true);
        UI.pack();
        UI.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    // Share button method
    private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
        getBlogText();
        shareContent();
    }//GEN-LAST:event_shareButtonActionPerformed

    // Opens infographics & videos window
    private void infografActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infografActionPerformed
        CI_UserInfographicAndVid UI = new CI_UserInfographicAndVid();
        UI.setVisible(true);
        UI.pack();
        UI.setLocationRelativeTo(null);

        this.dispose();    
    }//GEN-LAST:event_infografActionPerformed
    
    // Getter method for Blog content
    public String getBlogText() {
        return Blog.getText();
    }

    // Displays shared content in dashboard of Home page
    private void shareContent() {
        // Assuming you have an instance of UserInterface, replace UIInstance with your actual instance
        UserInterface UIInstance = new UserInterface();
        // Get the text from the CI_User Blog editor pane
        String blogText = getBlogText();
        // Set the HTML content in the UserInterface CItext editor pane
        UIInstance.setCItextHTML(blogText);        
        UIInstance.setVisible(true);
        UIInstance.setLocationRelativeTo(null);
        
        this.dispose();        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane Blog;
    private javax.swing.JButton InfoBtn;
    private javax.swing.JButton NewsFeedBtn;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton infograf;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton shareButton;
    // End of variables declaration//GEN-END:variables
}
